server:
  port: 8301

spring:
  application:
    name: BASE-Gateway
  cloud:
    gateway:
      routes:
        # 路由ID，保持唯一即可
        - id: BASE-Auth
          # 路由的目标地址，可以指定为HTTP地址，也可以通过lb://{微服务名称}来指定。
          # lb为load balance的缩写，微服务名称为注册中心中对应的微服务名称。
          # 比如将uri配置为lb://BASE-Auth的含义是，满足转发条件后，请求将均衡的转发到BASE-Auth微服务上
          uri: lb://BASE-Auth
          # 就是上面所说的谓词工厂。值为- Path=/auth/**表示请求Path以/auth开头的都会被匹配，然后转发到BASE-Auth服务上；
          predicates:
            - Path=/auth/**
          filters:
            # 指定添加Hystrix过滤器
            - name: Hystrix
              args:
                # 指定HystrixCommandKey为authfallback
                name: authfallback
                # fallbackUri指定了回退的重定向地址。
                fallbackUri: forward:/fallback/BASE-Auth
        - id: BASE-Server-System
          uri: lb://BASE-Server-System
          predicates:
            - Path=/system/**
          filters:
            - name: Hystrix
              args:
                name: systemfallback
                fallbackUri: forward:/fallback/BASE-Server-System
        - id: Base-Server-test
          uri: lb://Base-Server-Test
          predicates:
            - Path=/test/**
          filters:
            - name: Hystrix
              args:
                name: testfallback
                fallbackUri: forward:/fallback/BASE-Server-Test
      # filters为过滤器工厂，配置为- StripPrefix=1的意思是，请求转发前，将Path的内容截去前面一位。比如/auth/hello会被截取为/hello
      default-filters:
        - StripPrefix=1

eureka:
  instance:
    lease-renewal-interval-in-seconds: 20
  client:
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 3
    serviceUrl:
      defaultZone: http://admin:123456@localhost:8001/register/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

